# Generated by Django 6.0 on 2025-12-26 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_commentary_created_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="owner",
            new_name="author",
        ),
    ]
