# Generated by Django 6.0 on 2025-12-26 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_owner_post_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentary",
            old_name="user",
            new_name="author",
        ),
    ]
