# Generated by Django 6.0 on 2025-12-26 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_rename_user_commentary_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentary",
            old_name="content",
            new_name="text",
        ),
    ]
